name: "Main"
on: [push]
jobs:
  create-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Create PDF
        run: yarn build
      - name: Archive PDF
        uses: actions/upload-artifact@v3
        with:
          name: curriculum
          path: ./dist/Curriculum.pdf
  
      